---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: traefik
  name: traefik

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: traefik
  name: traefik
  namespace: traefik

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: traefik
  name: traefik-reconciler
  namespace: traefik
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-full-access
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:traefik:reconciler
- kind: ServiceAccount
  name: traefik
  namespace: traefik

